### ISSUE TITLE
can't install as assets

### ISSUE THREAD

**Issue by ulutomaz** [asachs01/sensu-go-twilio-handler#8]
I am trying to install sensu-go-twilio-handler as suggested, but getting this error below. 

```
ubuntu@admincontrol:~/PRODUCTION/twilio-sms-pusher/sensu-go-twilio-handler$ sensuctl asset add asachs01/sensu-go-twilio-handler
no version specified, using latest: 1.0.2
fetching bonsai asset: asachs01/sensu-go-twilio-handler:1.0.2
Error: error putting resource #0 with name "sensu-go-twilio-handler" and namespace "default" (/api/core/v2/namespaces/default/assets/asachs01%2Fsensu-go-twilio-handler): resource is invalid: SHA-512 checksum cannot be empty
ubuntu@admincontrol:~/PRODUCTION/twilio-sms-pusher/sensu-go-twilio-handler$
```

I really need the latest version 1.0.2, since I need this "multiple recepients" functionality. 

What can I do, to get it running? Install it directly on server and use it somehow "bypassing" the assets like approach? 

On Sensu page I can see that the last version has this issue
```
This asset has compilation errors
Version 1.0.2: missing GitHub release asset for sensu-go-twilio-handler_1.0.2_linux_arm64.tar.gz
```

Please, I would appreciate some feedback.

**Comment by asachs01** [comment]
@ulutomaz looks like it was an issue with Bonsai. Please give it a shot again.

**Comment by ulutomaz** [comment]
Great it works! Thanks for quick feedback.
